### ISSUE TITLE
Error when running runUnitTest.py

### ISSUE THREAD

**Issue by yuizi** [lbl-srg/EnergyPlusToFMU#55]
When I run runNnitTest.py on Windows 10 Pro (64bit), Python 3.8.8 (64bit), I get the following error message
It seems that PyFMI is causing the error, is there any workaround?

> PS C:\LBL\EnergyPlusToFMU-v3.1.0\bin> python .\runUnitTest.py
> The Path to the script file=C:\LBL\EnergyPlusToFMU-v3.1.0\Scripts\EnergyPlusToFMU.py.
> EnergyPlus version C:\EnergyPlusV8-7-0 was found. This version will be used for exporting and running EnergyPlus FMUs.  If you want to use a different version, provide the full path of the version now. Otherwise press return:
> The Path to the EnergyPlus version provided= does not exist.The EnergyPlus version found=C:\EnergyPlusV8-7-0 will be used.
> The Path to the IDD file=C:\EnergyPlusV8-7-0\Energy+.idd.
> The Path to the Weather file=C:\EnergyPlusV8-7-0\WeatherData\USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw.
> The Path to the example file=C:\LBL\EnergyPlusToFMU-v3.1.0\Examples\Schedule\_fmu-export-schedule.idf.
> Directory=C:\LBL\EnergyPlusToFMU-v3.1.0\bin\v_2 exists and will be deleted and recreated.
> fmu-export-write-model-desc.cpp
> app-cmdln-input.cpp
> app-cmdln-version.cpp
> fmu-export-idf-data.cpp
> fmu-export-write-vars-cfg.cpp
> fmu-export-prep-main.cpp
> ep-idd-map.cpp
> fileReader.cpp
> fileReaderData.cpp
> fileReaderDictionary.cpp
> digest-md5.cpp
> file-help.cpp
> string-help.cpp
> time-help.cpp
> utilReport.cpp
> xml-output-help.cpp
> ERROR from script file {utilManageCompileLink.py}
> Unable to delete directory {C:\LBL\EnergyPlusToFMU-v3.1.0\bin\v_2\bld-idf-to-fmu-export-prep-win-exe}
> The generated FMU file=C:\LBL\EnergyPlusToFMU-v3.1.0\bin\v_2\_fmu_export_schedule.fmu.
> Traceback (most recent call last):
>   File ".\runUnitTest.py", line 229, in <module>
>     run_fmu(FMU_PATH, i, exa)
>   File ".\runUnitTest.py", line 50, in run_fmu
>     model = load_fmu(fmu=fmu_path)
>   File "src\pyfmi\fmi.pyx", line 8295, in pyfmi.fmi.load_fmu
> pyfmi.fmi.FMUException: Could not locate the FMU in the specified directory.

**Comment by xavfa** [comment]
You have this message : 
ERROR from script file {utilManageCompileLink.py}
Unable to delete directory {C:\LBL\EnergyPlusToFMU-v3.1.0\bin\v_2\bld-idf-to-fmu-export-prep-win-exe}

My guess is that it refers to the issue posted before on some delay needed to release the folder to be deleted....By simply adding a time delay following the post i guess it will work

**Comment by tsnouidui** [comment]
@yuizi Are you still experiencing the same issue?

**Comment by terrancelu92** [comment]
> You have this message :
> ERROR from script file {utilManageCompileLink.py}
> Unable to delete directory {C:\LBL\EnergyPlusToFMU-v3.1.0\bin\v_2\bld-idf-to-fmu-export-prep-win-exe}
> 
> My guess is that it refers to the issue posted before on some delay needed to release the folder to be deleted....By simply adding a time delay following the post i guess it will work



> @yuizi Are you still experiencing the same issue?

Hello, I am also experiencing this issue with the error message:

```
ERROR from script file {utilManageCompileLink.py}
Unable to delete directory {C:\Users\luxi217\EnergyPlusToFMU-v3.1.0\Examples\Actuator\bld-idf-to-fmu-export-prep-win-exe}
```

**Comment by brathod2** [comment]
Hi everyone, 

I encountered the same issue while running it through Jupyter Notebook on Windows. I found passing '-L' argument as a temporary fix to our problem, as this prevents EnergyPlusToFMU.py from cleaning up the intermediate files which is exactly when we are seeing the error. 

`!D:/EnergyplusFMU/EnergyPlusToFMU-v3.1.0/Scripts/EnergyPlusToFMU.py -i C:/EnergyPlusV9-2-0/Energy+.idd -w C:/EnergyPlusV9-2-0/WeatherData/USA_NC_Raleigh-Durham.723060_TMY2.epw -a 1 -d -L D:/EnergyplusFMU/EnergyPlusToFMU-v3.1.0/Examples/Schedule/_fmu-export-schedule.idf`

Hope this helps! Thanks
